# Generated by Django 4.0.6 on 2023-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('date_range', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('max_salary', models.BigIntegerField()),
                ('min_salary', models.BigIntegerField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('number_of_openings', models.IntegerField()),
                ('work_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
