# Generated by Django 4.0.6 on 2023-02-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('number_of_openings', models.IntegerField()),
                ('work_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('posted_by', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('perk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perks', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.jobs')),
                ('stipend', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.jobs')),
                ('date_range', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('max_salary', models.BigIntegerField()),
                ('min_salary', models.BigIntegerField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.companysector')),
                ('industry', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spoc',
            fields=[
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.company')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.jobs')),
                ('date_posted', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('application_received', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nm_jobs.jobs')),
                ('perk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.perks')),
            ],
        ),
    ]
