# Generated by Django 4.0.6 on 2023-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='phone_no',
            field=models.BigIntegerField(default='9876543234'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='posted_by',
            field=models.CharField(default='achu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_type',
            field=models.CharField(max_length=100),
        ),
    ]
