# Generated by Django 3.2.16 on 2023-02-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perks',
            old_name='perks',
            new_name='perk',
        ),
    ]
