# Generated by Django 3.2.16 on 2023-02-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perks',
            name='perk_id',
        ),
    ]
