# Generated by Django 3.2.16 on 2023-02-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
