# Generated by Django 4.0.6 on 2023-02-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0002_jobs_email_jobs_phone_no_jobs_posted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('perk_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.jobs'),
        ),
    ]
