# Generated by Django 3.2.16 on 2023-02-24 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0002_rename_perks_perks_perk'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_range', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('max_salary', models.BigIntegerField()),
                ('min_salary', models.BigIntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.jobs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FullTime',
        ),
    ]
