# Generated by Django 4.0.6 on 2023-02-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0003_addons_alter_jobdetails_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.jobs'),
        ),
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perks', models.CharField(max_length=300)),
                ('perk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.addons')),
            ],
        ),
    ]
