# Generated by Django 4.0.6 on 2023-02-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nm_jobs', '0004_alter_addons_job_id_perks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('application_received', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.company')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Spoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.companysector')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipend', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nm_jobs.jobs')),
            ],
        ),
    ]
